[[menus.main]]
name = 'Home'
pageRef = '/'
url = '/'
weight = 10

[[menus.main]]
name = 'Work'
pageRef = 'work'
url = '/work'
weight = 20
    [[menus.main]]
    name = 'Shorts'
    pageRef = 'shorts'
    url = '/shorts'
    weight = 10
    parent = 'Work'

    [[menus.main]]
    name = 'Photography'
    pageRef = 'photography'
    url = '/photography'
    weight = 20
    parent = 'Work'

    [[menus.main]]
    name = 'Coding'
    pageRef = 'coding'
    url = '/coding'
    weight = 30
    parent = 'Work'

[[menus.main]]
name = 'Blog'
pageRef = 'blog'
url = '/blog'
weight = 30

[[menus.main]]
name = 'About'
pageRef = 'about'
url = '/about'
weight = 40