[[main]]
name = 'Home'
pageRef = '/'
weight = 10

[[main]]
name = 'Shorts'
pageRef = '/shorts'
weight = 20

[[main]]
name = 'Photography'
pageRef = '/photography'
weight = 30

[[main]]
name = 'Coding'
pageRef = '/coding'
weight = 40

[[main]]
name = 'Blog'
pageRef = '/blog'
weight = 50
