baseURL = 'https://soerensc.xyz/'
languageCode = 'en-US'
title = 'Sören Schmidt-Clausen'
theme = ["own_theme", "hugo-shortcode-gallery-master"]

[[menu.main]]
name = 'Work'
pageRef = '/work'
weight = 10
    [[menu.main]]
    name = 'Shorts'
    pageRef = 'shorts'
    weight = 10
    parent = 'Work'

    [[menu.main]]
    name = 'Stills'
    pageRef = 'stils'
    weight = 20
    parent = 'Work'
    
    [[menu.main]]
    name = 'Animations'
    pageRef = 'small_animations'
    weight = 30
    parent = 'Work'

    [[menu.main]]
    name = 'Photography'
    pageRef = 'photography'
    weight = 40
    parent = 'Work'

    [[menu.main]]
    name = 'Coding'
    pageRef = 'coding'
    weight = 50
    parent = 'Work'

[[menu.main]]
name = 'About'
pageRef = 'about'
weight = 20

[[menu.main]]
name = 'Notes'
pageRef = 'blog'
weight = 30

[[menu.main]]
name = 'Contact'
pageRef = 'contact'
weight = 40