baseURL = 'https://soerensc.xyz/'
languageCode = 'en-US'
title = 'Sören Schmidt-Clausen'
theme = ["own_theme", "hugo-shortcode-gallery-master"]

[[menu.main]]
name = 'Work'
pageRef = '/'
weight = 10
    [[menu.main]]
    name = 'Shorts'
    pageRef = 'work/shorts'
    weight = 10
    parent = 'Work'

    [[menu.main]]
    name = 'Stills'
    pageRef = 'work/stils'
    weight = 20
    parent = 'Work'
    
    [[menu.main]]
    name = 'Animations'
    pageRef = 'work/animations'
    weight = 30
    parent = 'Work'

    [[menu.main]]
    name = 'Photography'
    pageRef = 'work/photography'
    weight = 40
    parent = 'Work'

    [[menu.main]]
    name = 'Coding'
    pageRef = 'work/coding'
    weight = 50
    parent = 'Work'

[[menu.main]]
name = 'About'
pageRef = 'about'
weight = 20

[[menu.main]]
name = 'Notes'
pageRef = 'notes'
weight = 30

[[menu.main]]
name = 'Contact'
pageRef = 'contact'
weight = 40